---
# This Docker composition file is used to build and test the container

name: skeleton-docker

secrets:
  quote_txt:
    file: ./src/secrets/quote.txt

services:
  example:
    # Run the container normally
    build:
      # VERSION must be specified on the command line:
      # e.g., --build-arg VERSION=0.0.1
      context: .
      dockerfile: Dockerfile
    environment:
      - ECHO_MESSAGE=Hello World from Docker Compose!
    image: cisagov/example
    init: true
    ports:
      - mode: host
        protocol: tcp
        published: "8421"
        target: 8421
    restart: "no"
    secrets:
      - source: quote_txt
        target: quote.txt

  example-version:
    # Run the container to collect version information
    command: --version
    image: cisagov/example
    init: true
    restart: "no"
